### ISSUE TITLE
Serialize UTC?

### ISSUE THREAD

**Issue by kernel-io** [pichfl/ember-data-luxon-transforms#3]
Shouldn't we convert the DateTime back to UTC when we are serializing the object?
just in-case we set the datetime object to something non UTC?

i.e:

```javascript
import Transform from 'ember-data/transform'
import { DateTime } from 'ember-luxon'

export default Transform.extend({
    deserialize(serialized) {
        if (serialized === null) {
            return serialized
        }

        return DateTime.fromISO(serialized).toUTC()
    },

    serialize(deserialized) {
        if (deserialized === null) {
            return deserialized
        }

        return deserialized.toUTC().toISO()
    },
})
```

**Comment by pichfl** [comment]
Good point. Our use case didn't include the serializer part so far so it never came up. Could you provide a PR for this? Happy to merge it.

**Comment by kernel-io** [comment]
https://github.com/anfema/ember-data-luxon-transforms/pull/4
